server.port: 8081

spring:
  h2.console:
    enabled: true
    path: '/console'
  jpa.hibernate:
    ddl-auto: validate
  datasource:
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: ''
    url: 'jdbc:h2:file:C:/Users/karci/IdeaProjects/toDoApp/todoapp'
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: '*'