server.port: 8081

spring:
  h2.console:
    enabled: true
    path: '/console'
  jpa.hibernate:
    ddl-auto: create
  datasource:
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: ''
    url: 'jdbc:h2:file:C:/Users/karci/IdeaProjects/toDoApp/todoapp'

